---
- name: Installation de Docker et Nginx
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour de apt
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Installation des paquets requis
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present

    - name: Ajout de la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajout du dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Installation de Docker Engine
      apt:
        name: docker-ce
        state: present

    - name: Installation du module Python Docker (nécessaire pour Ansible)
      pip:
        name: docker

    - name: Lancement du conteneur Nginx
      docker_container:
        name: mon-serveur-web
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"